#!/usr/bin/env bash
# Script to install and setup root file for nginx
sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-default.html
sudo service nginx start
