#!/usr/bin/env bash
# Script to redirect to another page
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "24i\		rewrite ^/redirect_me https://youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
