#!/usr/bin/env bash
# Script to install Nginx server, redirect /redirect_me and customize 404 not found
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "25i\		error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
