#!/usr/bin/env bash
# Script to add custom headers to Nginx
apt update
server_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name_;
		add_headers X-Served-By \$hostname;
}"
echo "$server_config" > /etc/nginx/sites-enabled/default
service nginx restart
