#!/usr/bin/env bash
# Script to install and configure HAproxy to send traffic between two servers and distribute requests using roundrobin
apt update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get install -y haproxy=2.6.\*
apt update && apt upgrade -y
ufw allow 1344
sed -i "36i\frontend web_server\n\tbind *:80\n\tdefault_backend web_server" /etc/haproxy/haproxy.cfg
sed -i "40i\backend web_server\n\tbalance roundrobin\n\tserver 11359-web-01 3.236.55.133:80 check\n\tserver 11359-web-02 44.192.95.89:80 check" /etc/haproxy/haproxy.cfg
service haproxy restart
