#!/usr/bin/env bash
# Script to create a MySQL backup and compress to tar.gz
DBNAME=tyrell_corp
DATE=`date +%d-%m-%Y`
SQLFILE=backup.sql
mysqldump -uroot -p $2 $DBNAME > $SQLFILE
tar -czf $DATE.tar.gz $SQLFILE
