#!/usr/bin/env bash
# This script displays numbers from 1 to 100 but:
# - displays FizzBuzz when the number is a multiple of 3 and 5
# - displays Fizz when the number is a multiple of 3
# - displays Buzz when the number is a multiple of 5
# - otherwise displays the number
# - in a list format
n=1

while [ "$n" -le 100 ]; do


  if ! (( n % 3 )) && ! (( n % 5 )); then
    echo "FizzBuzz"
  elif ! (( n % 3 )); then
    echo "Fizz"
  elif ! (( n % 5 )); then
    echo "Buzz"
  else
    echo "$n"
  fi
  
  ((n++))
done
